/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s78801s80423.ui.internal.S78801s80423Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return S78801s80423Activator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
