/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.GreetingsImpl <em>Greetings</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.GreetingsImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGreetings()
   * @generated
   */
  int GREETINGS = 0;

  /**
   * The feature id for the '<em><b>Personlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREETINGS__PERSONLIST = 0;

  /**
   * The number of structural features of the '<em>Greetings</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREETINGS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RolleImpl <em>Rolle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RolleImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRolle()
   * @generated
   */
  int ROLLE = 1;

  /**
   * The feature id for the '<em><b>Rolle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLLE__ROLLE = 0;

  /**
   * The feature id for the '<em><b>Ziel</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLLE__ZIEL = 1;

  /**
   * The number of structural features of the '<em>Rolle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ZielImpl <em>Ziel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ZielImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getZiel()
   * @generated
   */
  int ZIEL = 2;

  /**
   * The feature id for the '<em><b>Ziel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL__ZIEL = 0;

  /**
   * The feature id for the '<em><b>Nutzen</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL__NUTZEN = 1;

  /**
   * The number of structural features of the '<em>Ziel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NutzenImpl <em>Nutzen</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NutzenImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNutzen()
   * @generated
   */
  int NUTZEN = 3;

  /**
   * The feature id for the '<em><b>Nutzen</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN__NUTZEN = 0;

  /**
   * The number of structural features of the '<em>Nutzen</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Greetings <em>Greetings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greetings</em>'.
   * @see org.xtext.example.mydsl.myDsl.Greetings
   * @generated
   */
  EClass getGreetings();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Greetings#getPersonlist <em>Personlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Personlist</em>'.
   * @see org.xtext.example.mydsl.myDsl.Greetings#getPersonlist()
   * @see #getGreetings()
   * @generated
   */
  EReference getGreetings_Personlist();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Rolle <em>Rolle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rolle</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rolle
   * @generated
   */
  EClass getRolle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Rolle#getRolle <em>Rolle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rolle</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rolle#getRolle()
   * @see #getRolle()
   * @generated
   */
  EAttribute getRolle_Rolle();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Rolle#getZiel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ziel</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rolle#getZiel()
   * @see #getRolle()
   * @generated
   */
  EReference getRolle_Ziel();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Ziel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ziel</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ziel
   * @generated
   */
  EClass getZiel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Ziel#getZiel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ziel</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ziel#getZiel()
   * @see #getZiel()
   * @generated
   */
  EAttribute getZiel_Ziel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Ziel#getNutzen <em>Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nutzen</em>'.
   * @see org.xtext.example.mydsl.myDsl.Ziel#getNutzen()
   * @see #getZiel()
   * @generated
   */
  EReference getZiel_Nutzen();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Nutzen <em>Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nutzen</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nutzen
   * @generated
   */
  EClass getNutzen();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Nutzen#getNutzen <em>Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nutzen</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nutzen#getNutzen()
   * @see #getNutzen()
   * @generated
   */
  EAttribute getNutzen_Nutzen();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.GreetingsImpl <em>Greetings</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.GreetingsImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getGreetings()
     * @generated
     */
    EClass GREETINGS = eINSTANCE.getGreetings();

    /**
     * The meta object literal for the '<em><b>Personlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREETINGS__PERSONLIST = eINSTANCE.getGreetings_Personlist();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RolleImpl <em>Rolle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RolleImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRolle()
     * @generated
     */
    EClass ROLLE = eINSTANCE.getRolle();

    /**
     * The meta object literal for the '<em><b>Rolle</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLLE__ROLLE = eINSTANCE.getRolle_Rolle();

    /**
     * The meta object literal for the '<em><b>Ziel</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROLLE__ZIEL = eINSTANCE.getRolle_Ziel();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ZielImpl <em>Ziel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ZielImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getZiel()
     * @generated
     */
    EClass ZIEL = eINSTANCE.getZiel();

    /**
     * The meta object literal for the '<em><b>Ziel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZIEL__ZIEL = eINSTANCE.getZiel_Ziel();

    /**
     * The meta object literal for the '<em><b>Nutzen</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZIEL__NUTZEN = eINSTANCE.getZiel_Nutzen();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NutzenImpl <em>Nutzen</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NutzenImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNutzen()
     * @generated
     */
    EClass NUTZEN = eINSTANCE.getNutzen();

    /**
     * The meta object literal for the '<em><b>Nutzen</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUTZEN__NUTZEN = eINSTANCE.getNutzen_Nutzen();

  }

} //MyDslPackage
