/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nutzen</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Nutzen#getNutzen <em>Nutzen</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNutzen()
 * @model
 * @generated
 */
public interface Nutzen extends EObject
{
  /**
   * Returns the value of the '<em><b>Nutzen</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nutzen</em>' attribute.
   * @see #setNutzen(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNutzen_Nutzen()
   * @model
   * @generated
   */
  String getNutzen();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Nutzen#getNutzen <em>Nutzen</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nutzen</em>' attribute.
   * @see #getNutzen()
   * @generated
   */
  void setNutzen(String value);

} // Nutzen
