/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rolle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Rolle#getRolle <em>Rolle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Rolle#getZiel <em>Ziel</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRolle()
 * @model
 * @generated
 */
public interface Rolle extends EObject
{
  /**
   * Returns the value of the '<em><b>Rolle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rolle</em>' attribute.
   * @see #setRolle(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRolle_Rolle()
   * @model
   * @generated
   */
  String getRolle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Rolle#getRolle <em>Rolle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rolle</em>' attribute.
   * @see #getRolle()
   * @generated
   */
  void setRolle(String value);

  /**
   * Returns the value of the '<em><b>Ziel</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Ziel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ziel</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRolle_Ziel()
   * @model containment="true"
   * @generated
   */
  EList<Ziel> getZiel();

} // Rolle
