/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ziel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Ziel#getZiel <em>Ziel</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Ziel#getNutzen <em>Nutzen</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getZiel()
 * @model
 * @generated
 */
public interface Ziel extends EObject
{
  /**
   * Returns the value of the '<em><b>Ziel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ziel</em>' attribute.
   * @see #setZiel(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getZiel_Ziel()
   * @model
   * @generated
   */
  String getZiel();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Ziel#getZiel <em>Ziel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ziel</em>' attribute.
   * @see #getZiel()
   * @generated
   */
  void setZiel(String value);

  /**
   * Returns the value of the '<em><b>Nutzen</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Nutzen}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nutzen</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getZiel_Nutzen()
   * @model containment="true"
   * @generated
   */
  EList<Nutzen> getNutzen();

} // Ziel
