/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s78801s80423.ui.internal.S78801s80423Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(S78801s80423Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		S78801s80423Activator activator = S78801s80423Activator.getInstance();
		return activator != null ? activator.getInjector(S78801s80423Activator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
